export const mockData = [
  {
    firstName: 'Perrine',
    lastName: 'Spykins',
    email: 'pspykins0@alexa.com',
    favoriteAnimal: 'European shelduck',
    birthday: '12/21/1999',
  },
  {
    firstName: 'Keriann',
    lastName: 'Bunting',
    email: 'kbunting1@over-blog.com',
    favoriteAnimal: 'Robin, white-throated',
    birthday: '06/03/2014',
  },
  {
    firstName: 'Devora',
    lastName: 'Geaveny',
    email: 'dgeaveny2@nationalgeographic.com',
    favoriteAnimal: 'Canadian river otter',
    birthday: '10/16/2002',
  },
  {
    firstName: 'Auberta',
    lastName: 'McIndrew',
    email: 'amcindrew3@google.ca',
    favoriteAnimal: 'Chital',
    birthday: '02/14/2012',
  },
  {
    firstName: 'Corey',
    lastName: 'McGreal',
    email: 'cmcgreal4@un.org',
    favoriteAnimal: 'Fox, silver-backed',
    birthday: '08/27/1983',
  },
  {
    firstName: 'Ryann',
    lastName: 'Utteridge',
    email: 'rutteridge5@4shared.com',
    favoriteAnimal: 'Armadillo, giant',
    birthday: '05/10/2007',
  },
  {
    firstName: 'Gail',
    lastName: 'Ingyon',
    email: 'gingyon6@php.net',
    favoriteAnimal: 'Guerza',
    birthday: '08/11/1981',
  },
  {
    firstName: 'Amaleta',
    lastName: 'Edworthye',
    email: 'aedworthye7@ca.gov',
    favoriteAnimal: 'Dragon, asian water',
    birthday: '08/05/1982',
  },
  {
    firstName: 'Ali',
    lastName: 'Giercke',
    email: 'agiercke8@exblog.jp',
    favoriteAnimal: 'Long-finned pilot whale',
    birthday: '09/30/1981',
  },
  {
    firstName: 'Timi',
    lastName: 'Zanelli',
    email: 'tzanelli9@nationalgeographic.com',
    favoriteAnimal: 'Dama wallaby',
    birthday: '11/15/2006',
  },
  {
    firstName: 'Niven',
    lastName: 'Snailham',
    email: 'nsnailhama@spiegel.de',
    favoriteAnimal: 'Two-toed sloth',
    birthday: '12/05/2017',
  },
  {
    firstName: 'Korie',
    lastName: 'Saphir',
    email: 'ksaphirb@hugedomains.com',
    favoriteAnimal: 'Weaver, white-browed sparrow',
    birthday: '02/24/1997',
  },
  {
    firstName: 'Mathian',
    lastName: 'Goodwyn',
    email: 'mgoodwync@weather.com',
    favoriteAnimal: 'Lemur, ring-tailed',
    birthday: '04/12/1997',
  },
  {
    firstName: 'Alon',
    lastName: 'Harbard',
    email: 'aharbardd@arstechnica.com',
    favoriteAnimal: 'Lion, southern sea',
    birthday: '03/23/1989',
  },
  {
    firstName: 'Emlyn',
    lastName: 'Cowup',
    email: 'ecowupe@dion.ne.jp',
    favoriteAnimal: 'African wild cat',
    birthday: '01/26/2009',
  },
  {
    firstName: 'Jarad',
    lastName: 'Clardge',
    email: 'jclardgef@nih.gov',
    favoriteAnimal: 'Crane, sarus',
    birthday: '10/06/2014',
  },
  {
    firstName: 'Cody',
    lastName: 'Goucher',
    email: 'cgoucherg@jimdo.com',
    favoriteAnimal: 'Eurasian beaver',
    birthday: '11/27/1996',
  },
  {
    firstName: 'Carmine',
    lastName: 'Whittleton',
    email: 'cwhittletonh@constantcontact.com',
    favoriteAnimal: 'Gecko (unidentified)',
    birthday: '04/02/2011',
  },
  {
    firstName: 'Julie',
    lastName: 'Bushe',
    email: 'jbushei@icq.com',
    favoriteAnimal: 'Horned lark',
    birthday: '05/19/2014',
  },
  {
    firstName: 'Alphard',
    lastName: 'Greeveson',
    email: 'agreevesonj@auda.org.au',
    favoriteAnimal: 'Eagle, african fish',
    birthday: '06/02/2002',
  },
  {
    firstName: 'Alexandrina',
    lastName: 'Demer',
    email: 'ademerk@ning.com',
    favoriteAnimal: 'Stork, woolly-necked',
    birthday: '10/17/2016',
  },
  {
    firstName: 'Conway',
    lastName: 'Chicchelli',
    email: 'cchicchellil@goodreads.com',
    favoriteAnimal: 'Eastern indigo snake',
    birthday: '01/25/1990',
  },
  {
    firstName: 'Tarrance',
    lastName: 'Dumberrill',
    email: 'tdumberrillm@ucoz.ru',
    favoriteAnimal: 'Glider, squirrel',
    birthday: '07/28/1997',
  },
  {
    firstName: 'Ilyse',
    lastName: 'Grubey',
    email: 'igrubeyn@csmonitor.com',
    favoriteAnimal: 'Siskin, yellow-rumped',
    birthday: '09/27/2013',
  },
  {
    firstName: 'Clio',
    lastName: 'Southgate',
    email: 'csouthgateo@ebay.com',
    favoriteAnimal: 'Savannah deer (unidentified)',
    birthday: '12/03/1998',
  },
  {
    firstName: 'Bobbye',
    lastName: 'Antonacci',
    email: 'bantonaccip@yelp.com',
    favoriteAnimal: 'Iguana, marine',
    birthday: '12/18/1988',
  },
  {
    firstName: 'Angeline',
    lastName: 'Pargeter',
    email: 'apargeterq@lulu.com',
    favoriteAnimal: 'Kingfisher, pied',
    birthday: '04/23/1990',
  },
  {
    firstName: 'Ambrose',
    lastName: 'Crabtree',
    email: 'acrabtreer@stumbleupon.com',
    favoriteAnimal: 'Caiman, spectacled',
    birthday: '09/26/1983',
  },
  {
    firstName: 'Ware',
    lastName: 'Caldecourt',
    email: 'wcaldecourts@trellian.com',
    favoriteAnimal: 'Greater flamingo',
    birthday: '06/02/2008',
  },
  {
    firstName: 'Paxton',
    lastName: 'Easson',
    email: 'peassont@prlog.org',
    favoriteAnimal: 'Tortoise, asian foreset',
    birthday: '04/30/1985',
  },
  {
    firstName: 'Katrina',
    lastName: 'Bronot',
    email: 'kbronotu@hexun.com',
    favoriteAnimal: 'Asian water dragon',
    birthday: '05/30/2005',
  },
  {
    firstName: 'Filippa',
    lastName: 'Pettitt',
    email: 'fpettittv@zdnet.com',
    favoriteAnimal: 'Glossy ibis',
    birthday: '03/07/2011',
  },
  {
    firstName: 'Natal',
    lastName: 'Nevins',
    email: 'nnevinsw@de.vu',
    favoriteAnimal: 'Baleen whale',
    birthday: '03/12/2013',
  },
  {
    firstName: 'Vivianna',
    lastName: 'Jopling',
    email: 'vjoplingx@studiopress.com',
    favoriteAnimal: 'Cape wild cat',
    birthday: '01/31/2007',
  },
  {
    firstName: 'Kacy',
    lastName: 'Duguid',
    email: 'kduguidy@netvibes.com',
    favoriteAnimal: 'Gray duiker',
    birthday: '12/28/1990',
  },
  {
    firstName: 'Fabio',
    lastName: 'Tipton',
    email: 'ftiptonz@theglobeandmail.com',
    favoriteAnimal: 'Glossy starling (unidentified)',
    birthday: '02/01/1993',
  },
  {
    firstName: 'Livvie',
    lastName: 'Smee',
    email: 'lsmee10@bloglovin.com',
    favoriteAnimal: "Zorro, azara's",
    birthday: '12/20/2008',
  },
  {
    firstName: 'Lilias',
    lastName: 'Stocks',
    email: 'lstocks11@usatoday.com',
    favoriteAnimal: 'Antelope, sable',
    birthday: '10/03/1996',
  },
  {
    firstName: 'Rik',
    lastName: 'Hollingby',
    email: 'rhollingby12@nature.com',
    favoriteAnimal: 'Skink, african',
    birthday: '01/22/2012',
  },
  {
    firstName: 'Pincas',
    lastName: 'Espine',
    email: 'pespine13@csmonitor.com',
    favoriteAnimal: 'Goose, snow',
    birthday: '12/03/1986',
  },
  {
    firstName: 'Farlee',
    lastName: 'Seagar',
    email: 'fseagar14@storify.com',
    favoriteAnimal: 'Cat, toddy',
    birthday: '09/30/1981',
  },
  {
    firstName: 'Karena',
    lastName: 'Heggman',
    email: 'kheggman15@goo.gl',
    favoriteAnimal: 'Stick insect',
    birthday: '09/22/1993',
  },
  {
    firstName: 'Modesty',
    lastName: 'Timbs',
    email: 'mtimbs16@cocolog-nifty.com',
    favoriteAnimal: 'Red-breasted cockatoo',
    birthday: '07/15/2010',
  },
  {
    firstName: 'Gloriane',
    lastName: 'Canniffe',
    email: 'gcanniffe17@discuz.net',
    favoriteAnimal: 'Western palm tanager (unidentified)',
    birthday: '01/27/2006',
  },
  {
    firstName: 'Elizabet',
    lastName: 'Giovannini',
    email: 'egiovannini18@economist.com',
    favoriteAnimal: 'Tawny frogmouth',
    birthday: '06/16/1984',
  },
  {
    firstName: 'Flo',
    lastName: 'Saich',
    email: 'fsaich19@chronoengine.com',
    favoriteAnimal: 'Red-tailed hawk',
    birthday: '03/25/2001',
  },
  {
    firstName: 'Claudie',
    lastName: 'Lukins',
    email: 'clukins1a@friendfeed.com',
    favoriteAnimal: 'Black-tailed tree creeper',
    birthday: '08/07/2012',
  },
  {
    firstName: 'Cahra',
    lastName: 'Mallett',
    email: 'cmallett1b@techcrunch.com',
    favoriteAnimal: 'Red-breasted cockatoo',
    birthday: '09/19/2013',
  },
  {
    firstName: 'Balduin',
    lastName: 'Croutear',
    email: 'bcroutear1c@nyu.edu',
    favoriteAnimal: 'Water moccasin',
    birthday: '10/16/1992',
  },
  {
    firstName: 'Lyssa',
    lastName: 'Bowstead',
    email: 'lbowstead1d@go.com',
    favoriteAnimal: 'Common grenadier',
    birthday: '11/05/2019',
  },
  {
    firstName: 'Donnie',
    lastName: 'Kenworthy',
    email: 'dkenworthy1e@cdc.gov',
    favoriteAnimal: 'Gecko, ring-tailed',
    birthday: '12/02/2011',
  },
  {
    firstName: 'Lorna',
    lastName: 'Jackman',
    email: 'ljackman1f@g.co',
    favoriteAnimal: 'Seal, northern fur',
    birthday: '10/31/2014',
  },
  {
    firstName: 'Matteo',
    lastName: 'Jepperson',
    email: 'mjepperson1g@amazon.co.jp',
    favoriteAnimal: 'Dragon, komodo',
    birthday: '07/09/1987',
  },
  {
    firstName: 'Riley',
    lastName: 'Hollingshead',
    email: 'rhollingshead1h@topsy.com',
    favoriteAnimal: 'Grison',
    birthday: '05/16/1986',
  },
  {
    firstName: 'Nydia',
    lastName: 'Bridge',
    email: 'nbridge1i@newyorker.com',
    favoriteAnimal: 'Cobra (unidentified)',
    birthday: '12/17/1990',
  },
  {
    firstName: 'Ruddie',
    lastName: 'Metherell',
    email: 'rmetherell1j@opera.com',
    favoriteAnimal: 'Lizard, desert spiny',
    birthday: '07/27/2009',
  },
  {
    firstName: 'Deirdre',
    lastName: 'Josefs',
    email: 'djosefs1k@hostgator.com',
    favoriteAnimal: 'Sandgrouse, yellow-throated',
    birthday: '10/31/2019',
  },
  {
    firstName: 'Nilson',
    lastName: 'Laver',
    email: 'nlaver1l@blogspot.com',
    favoriteAnimal: 'Kafue flats lechwe',
    birthday: '07/30/2006',
  },
  {
    firstName: 'Julina',
    lastName: 'Walthew',
    email: 'jwalthew1m@parallels.com',
    favoriteAnimal: 'Hedgehog, south african',
    birthday: '12/16/1981',
  },
  {
    firstName: 'Angelia',
    lastName: 'Babbs',
    email: 'ababbs1n@acquirethisname.com',
    favoriteAnimal: 'Frilled dragon',
    birthday: '07/18/1986',
  },
  {
    firstName: 'Elisa',
    lastName: 'Hamblington',
    email: 'ehamblington1o@studiopress.com',
    favoriteAnimal: 'Red-knobbed coot',
    birthday: '02/05/1992',
  },
  {
    firstName: 'Vinita',
    lastName: 'Whitington',
    email: 'vwhitington1p@economist.com',
    favoriteAnimal: 'Red-billed hornbill',
    birthday: '10/20/1993',
  },
  {
    firstName: 'Kippie',
    lastName: 'Witling',
    email: 'kwitling1q@angelfire.com',
    favoriteAnimal: 'Uinta ground squirrel',
    birthday: '07/01/2017',
  },
  {
    firstName: 'Judah',
    lastName: 'Cordery',
    email: 'jcordery1r@joomla.org',
    favoriteAnimal: 'Bushpig',
    birthday: '02/10/2017',
  },
  {
    firstName: 'Gerrilee',
    lastName: 'Valiant',
    email: 'gvaliant1s@cnn.com',
    favoriteAnimal: 'Giraffe',
    birthday: '03/24/2016',
  },
  {
    firstName: 'Elwira',
    lastName: 'Clemence',
    email: 'eclemence1t@meetup.com',
    favoriteAnimal: 'Black bear',
    birthday: '01/23/1983',
  },
  {
    firstName: 'Randa',
    lastName: 'Edgeworth',
    email: 'redgeworth1u@mashable.com',
    favoriteAnimal: 'Ostrich',
    birthday: '03/12/2017',
  },
  {
    firstName: 'Annaliese',
    lastName: 'Bertomieu',
    email: 'abertomieu1v@ox.ac.uk',
    favoriteAnimal: 'Glossy starling (unidentified)',
    birthday: '10/10/2019',
  },
  {
    firstName: 'Nikki',
    lastName: "O'Noulane",
    email: 'nonoulane1w@360.cn',
    favoriteAnimal: 'Red phalarope',
    birthday: '10/09/2010',
  },
  {
    firstName: 'Iormina',
    lastName: 'Keyzor',
    email: 'ikeyzor1x@indiegogo.com',
    favoriteAnimal: 'African wild cat',
    birthday: '02/01/2007',
  },
  {
    firstName: 'Rae',
    lastName: 'Toopin',
    email: 'rtoopin1y@rakuten.co.jp',
    favoriteAnimal: 'Legaan, Monitor (unidentified)',
    birthday: '03/16/2001',
  },
  {
    firstName: 'Carlie',
    lastName: 'Bilverstone',
    email: 'cbilverstone1z@paginegialle.it',
    favoriteAnimal: 'Lynx, african',
    birthday: '04/29/2006',
  },
  {
    firstName: 'Coraline',
    lastName: 'MacKibbon',
    email: 'cmackibbon20@businessinsider.com',
    favoriteAnimal: 'Black swan',
    birthday: '11/21/2020',
  },
  {
    firstName: 'Griff',
    lastName: 'Colenutt',
    email: 'gcolenutt21@nih.gov',
    favoriteAnimal: 'River wallaby',
    birthday: '04/20/1990',
  },
  {
    firstName: 'Alberta',
    lastName: 'Antonat',
    email: 'aantonat22@sohu.com',
    favoriteAnimal: 'Mongoose, eastern dwarf',
    birthday: '08/24/2012',
  },
  {
    firstName: 'Caspar',
    lastName: 'Mitcheson',
    email: 'cmitcheson23@gizmodo.com',
    favoriteAnimal: 'Robin, kalahari scrub',
    birthday: '02/10/2008',
  },
  {
    firstName: 'Marten',
    lastName: 'Halwill',
    email: 'mhalwill24@51.la',
    favoriteAnimal: 'White-faced whistling duck',
    birthday: '01/25/1987',
  },
  {
    firstName: 'Erminie',
    lastName: 'Ringsell',
    email: 'eringsell25@yellowbook.com',
    favoriteAnimal: 'Dolphin, striped',
    birthday: '07/26/1983',
  },
  {
    firstName: 'Zahara',
    lastName: 'Feldstein',
    email: 'zfeldstein26@hibu.com',
    favoriteAnimal: 'Flamingo, greater',
    birthday: '08/18/2011',
  },
  {
    firstName: 'Henrik',
    lastName: 'Nason',
    email: 'hnason27@nih.gov',
    favoriteAnimal: 'Wolf, timber',
    birthday: '09/07/2003',
  },
  {
    firstName: 'Bambie',
    lastName: 'McAlroy',
    email: 'bmcalroy28@ask.com',
    favoriteAnimal: 'Fox, savanna',
    birthday: '03/17/2004',
  },
  {
    firstName: 'Coriss',
    lastName: 'Postins',
    email: 'cpostins29@pbs.org',
    favoriteAnimal: 'White-lipped peccary',
    birthday: '03/23/1995',
  },
  {
    firstName: 'Rina',
    lastName: 'Yarranton',
    email: 'ryarranton2a@phoca.cz',
    favoriteAnimal: 'Bird, red-billed tropic',
    birthday: '10/16/1993',
  },
  {
    firstName: 'Nicolas',
    lastName: 'Bahike',
    email: 'nbahike2b@sbwire.com',
    favoriteAnimal: 'South African hedgehog',
    birthday: '07/15/1986',
  },
  {
    firstName: 'Klemens',
    lastName: 'Jzak',
    email: 'kjzak2c@alibaba.com',
    favoriteAnimal: 'Gull, dusky',
    birthday: '07/20/2020',
  },
  {
    firstName: 'Tina',
    lastName: 'Pes',
    email: 'tpes2d@cnbc.com',
    favoriteAnimal: "Barbet, levaillant's",
    birthday: '03/12/1985',
  },
  {
    firstName: 'Dominique',
    lastName: 'Cotgrove',
    email: 'dcotgrove2e@sfgate.com',
    favoriteAnimal: 'Heron, giant',
    birthday: '12/02/1999',
  },
  {
    firstName: 'Coreen',
    lastName: 'Klejin',
    email: 'cklejin2f@hugedomains.com',
    favoriteAnimal: 'Booby, blue-faced',
    birthday: '05/17/1981',
  },
  {
    firstName: 'Van',
    lastName: 'Laws',
    email: 'vlaws2g@com.com',
    favoriteAnimal: 'Gerbil (unidentified)',
    birthday: '08/07/1984',
  },
  {
    firstName: 'Nikki',
    lastName: 'Lambarton',
    email: 'nlambarton2h@google.de',
    favoriteAnimal: 'Cockatoo, red-tailed',
    birthday: '01/11/1995',
  },
  {
    firstName: 'Anabelle',
    lastName: 'Quiddinton',
    email: 'aquiddinton2i@cdc.gov',
    favoriteAnimal: 'Malachite kingfisher',
    birthday: '09/24/2003',
  },
  {
    firstName: 'Teddy',
    lastName: 'Kirvin',
    email: 'tkirvin2j@state.gov',
    favoriteAnimal: 'Lion, steller sea',
    birthday: '02/20/2019',
  },
  {
    firstName: 'Carolann',
    lastName: 'Dalston',
    email: 'cdalston2k@webnode.com',
    favoriteAnimal: 'Civet, small-toothed palm',
    birthday: '01/09/1993',
  },
  {
    firstName: 'Burl',
    lastName: 'Treffrey',
    email: 'btreffrey2l@phpbb.com',
    favoriteAnimal: 'Dromedary camel',
    birthday: '01/02/1997',
  },
  {
    firstName: 'Korrie',
    lastName: 'Billany',
    email: 'kbillany2m@a8.net',
    favoriteAnimal: 'Olive baboon',
    birthday: '05/15/1990',
  },
  {
    firstName: 'Jeramie',
    lastName: 'Thornbarrow',
    email: 'jthornbarrow2n@furl.net',
    favoriteAnimal: 'Crake, african black',
    birthday: '12/25/2012',
  },
  {
    firstName: 'Storm',
    lastName: 'Trenoweth',
    email: 'strenoweth2o@statcounter.com',
    favoriteAnimal: 'Malleefowl',
    birthday: '12/02/1990',
  },
  {
    firstName: 'Oberon',
    lastName: 'Shannahan',
    email: 'oshannahan2p@wisc.edu',
    favoriteAnimal: 'Scarlet macaw',
    birthday: '05/21/2009',
  },
  {
    firstName: 'Sibella',
    lastName: 'Splevings',
    email: 'ssplevings2q@webeden.co.uk',
    favoriteAnimal: 'Lizard, collared',
    birthday: '12/16/2017',
  },
  {
    firstName: 'Ulrike',
    lastName: 'Brewitt',
    email: 'ubrewitt2r@gov.uk',
    favoriteAnimal: 'Eastern grey kangaroo',
    birthday: '05/11/2012',
  },
]
