export const mockData = [
  {
    id: 1,
    firstName: 'Merrili',
    lastName: 'Lorek',
    email: 'mlorek0@g.co',
    favoriteAnimal: 'Possum, pygmy',
  },
  {
    id: 2,
    firstName: 'Selestina',
    lastName: 'Give',
    email: 'sgive1@google.com.au',
    favoriteAnimal: 'Cockatoo, long-billed',
  },
  {
    id: 3,
    firstName: 'Sander',
    lastName: 'Redit',
    email: 'sredit2@merriam-webster.com',
    favoriteAnimal: 'Kinkajou',
  },
  {
    id: 4,
    firstName: 'Helli',
    lastName: 'Iredale',
    email: 'hiredale3@ucsd.edu',
    favoriteAnimal: 'Weaver, chestnut',
  },
  {
    id: 5,
    firstName: 'Jeremiah',
    lastName: 'Harrie',
    email: 'jharrie4@weibo.com',
    favoriteAnimal: 'Eagle owl (unidentified)',
  },
  {
    id: 6,
    firstName: 'Orbadiah',
    lastName: 'Barlass',
    email: 'obarlass5@soup.io',
    favoriteAnimal: 'Defassa waterbuck',
  },
  {
    id: 7,
    firstName: 'Mellicent',
    lastName: 'Galton',
    email: 'mgalton6@feedburner.com',
    favoriteAnimal: 'Whale, long-finned pilot',
  },
  {
    id: 8,
    firstName: 'Leland',
    lastName: 'Fullerton',
    email: 'lfullerton7@examiner.com',
    favoriteAnimal: 'North American porcupine',
  },
  {
    id: 9,
    firstName: 'Kary',
    lastName: 'Brehat',
    email: 'kbrehat8@1und1.de',
    favoriteAnimal: 'Glider, squirrel',
  },
  {
    id: 10,
    firstName: 'Dru',
    lastName: 'Skentelbury',
    email: 'dskentelbury9@unc.edu',
    favoriteAnimal: 'Common long-nosed armadillo',
  },
  {
    id: 11,
    firstName: 'Salvidor',
    lastName: 'Prangle',
    email: 'spranglea@prnewswire.com',
    favoriteAnimal: 'Magellanic penguin',
  },
  {
    id: 12,
    firstName: 'Royall',
    lastName: 'Keaves',
    email: 'rkeavesb@jalbum.net',
    favoriteAnimal: 'Common waterbuck',
  },
  {
    id: 13,
    firstName: 'Lottie',
    lastName: 'Randles',
    email: 'lrandlesc@tiny.cc',
    favoriteAnimal: 'Rhea, gray',
  },
  {
    id: 14,
    firstName: 'Noak',
    lastName: 'McKeaveney',
    email: 'nmckeaveneyd@sourceforge.net',
    favoriteAnimal: 'Kori bustard',
  },
  {
    id: 15,
    firstName: 'Oralia',
    lastName: 'Wraith',
    email: 'owraithe@com.com',
    favoriteAnimal: 'Southern white-crowned shrike',
  },
  {
    id: 16,
    firstName: 'Rosalynd',
    lastName: 'Chasteney',
    email: 'rchasteneyf@patch.com',
    favoriteAnimal: 'Javanese cormorant',
  },
  {
    id: 17,
    firstName: 'Pierce',
    lastName: 'Bonass',
    email: 'pbonassg@netscape.com',
    favoriteAnimal: 'Rhea, greater',
  },
  {
    id: 18,
    firstName: 'Yuri',
    lastName: 'Sarra',
    email: 'ysarrah@networkadvertising.org',
    favoriteAnimal: 'Roseat flamingo',
  },
  {
    id: 19,
    firstName: 'Odetta',
    lastName: 'Matussevich',
    email: 'omatussevichi@goodreads.com',
    favoriteAnimal: 'European stork',
  },
  {
    id: 20,
    firstName: 'Waylan',
    lastName: 'Lamberth',
    email: 'wlamberthj@latimes.com',
    favoriteAnimal: 'Hippopotamus',
  },
  {
    id: 21,
    firstName: 'Dorris',
    lastName: 'Evans',
    email: 'devansk@europa.eu',
    favoriteAnimal: 'Vulture, griffon',
  },
  {
    id: 22,
    firstName: 'Zora',
    lastName: 'Kiossel',
    email: 'zkiossell@paypal.com',
    favoriteAnimal: 'Yellow-crowned night heron',
  },
  {
    id: 23,
    firstName: 'Susanne',
    lastName: 'Seabright',
    email: 'sseabrightm@vistaprint.com',
    favoriteAnimal: 'Canada goose',
  },
  {
    id: 24,
    firstName: 'Kassia',
    lastName: 'Deller',
    email: 'kdellern@plala.or.jp',
    favoriteAnimal: 'Great white pelican',
  },
  {
    id: 25,
    firstName: 'Ronny',
    lastName: 'Firsby',
    email: 'rfirsbyo@rakuten.co.jp',
    favoriteAnimal: 'Southern hairy-nosed wombat',
  },
  {
    id: 26,
    firstName: 'Belva',
    lastName: 'Kerss',
    email: 'bkerssp@chronoengine.com',
    favoriteAnimal: 'Heron, giant',
  },
  {
    id: 27,
    firstName: 'Errick',
    lastName: 'Tome',
    email: 'etomeq@tripod.com',
    favoriteAnimal: 'Moorhen, purple',
  },
  {
    id: 28,
    firstName: 'Debby',
    lastName: 'Iacobacci',
    email: 'diacobaccir@wikispaces.com',
    favoriteAnimal: 'Heron, black-crowned night',
  },
  {
    id: 29,
    firstName: 'Jacklin',
    lastName: 'Lewin',
    email: 'jlewins@dot.gov',
    favoriteAnimal: 'South American puma',
  },
  {
    id: 30,
    firstName: 'Mattheus',
    lastName: 'Gregon',
    email: 'mgregont@cnbc.com',
    favoriteAnimal: 'Moorhen, purple',
  },
  {
    id: 31,
    firstName: 'Lil',
    lastName: 'Kemp',
    email: 'lkempu@addtoany.com',
    favoriteAnimal: 'Buffalo, asian water',
  },
  {
    id: 32,
    firstName: 'Roz',
    lastName: 'Tipton',
    email: 'rtiptonv@simplemachines.org',
    favoriteAnimal: 'White-necked raven',
  },
  {
    id: 33,
    firstName: 'Alfons',
    lastName: 'Boas',
    email: 'aboasw@ameblo.jp',
    favoriteAnimal: "Squirrel, richardson's ground",
  },
  {
    id: 34,
    firstName: 'Andris',
    lastName: 'Maccree',
    email: 'amaccreex@google.ru',
    favoriteAnimal: 'White-tailed deer',
  },
  {
    id: 35,
    firstName: 'Knox',
    lastName: 'Goullee',
    email: 'kgoulleey@histats.com',
    favoriteAnimal: 'Marmot, hoary',
  },
  {
    id: 36,
    firstName: 'Willyt',
    lastName: 'Tebb',
    email: 'wtebbz@marriott.com',
    favoriteAnimal: 'Manatee',
  },
  {
    id: 37,
    firstName: 'Jefferson',
    lastName: 'Jeff',
    email: 'jjeff10@nps.gov',
    favoriteAnimal: 'Caiman, spectacled',
  },
  {
    id: 38,
    firstName: 'Kerrin',
    lastName: 'Whittick',
    email: 'kwhittick11@sohu.com',
    favoriteAnimal: 'American woodcock',
  },
  {
    id: 39,
    firstName: 'Hilliary',
    lastName: 'Daynter',
    email: 'hdaynter12@wikipedia.org',
    favoriteAnimal: 'Kinkajou',
  },
  {
    id: 40,
    firstName: 'Karl',
    lastName: 'Stolz',
    email: 'kstolz13@drupal.org',
    favoriteAnimal: 'Brown capuchin',
  },
  {
    id: 41,
    firstName: 'Delmore',
    lastName: 'Millson',
    email: 'dmillson14@livejournal.com',
    favoriteAnimal: 'Hawk, red-tailed',
  },
  {
    id: 42,
    firstName: 'Tailor',
    lastName: 'Hanlin',
    email: 'thanlin15@reference.com',
    favoriteAnimal: 'Cape Barren goose',
  },
  {
    id: 43,
    firstName: 'Rutger',
    lastName: 'Kelley',
    email: 'rkelley16@ox.ac.uk',
    favoriteAnimal: 'American woodcock',
  },
  {
    id: 44,
    firstName: 'Rana',
    lastName: 'Napoli',
    email: 'rnapoli17@nasa.gov',
    favoriteAnimal: 'Gull, herring',
  },
  {
    id: 45,
    firstName: 'Iago',
    lastName: 'Foskett',
    email: 'ifoskett18@tuttocitta.it',
    favoriteAnimal: 'Emu',
  },
  {
    id: 46,
    firstName: 'Marita',
    lastName: 'Hounsom',
    email: 'mhounsom19@omniture.com',
    favoriteAnimal: 'Antelope, four-horned',
  },
  {
    id: 47,
    firstName: 'Jeane',
    lastName: 'Bahl',
    email: 'jbahl1a@wsj.com',
    favoriteAnimal: 'Springbok',
  },
  {
    id: 48,
    firstName: 'Imogene',
    lastName: 'Northrop',
    email: 'inorthrop1b@imageshack.us',
    favoriteAnimal: 'Penguin, fairy',
  },
  {
    id: 49,
    firstName: 'Dania',
    lastName: 'Marrion',
    email: 'dmarrion1c@mozilla.com',
    favoriteAnimal: 'Old world fruit bat (unidentified)',
  },
  {
    id: 50,
    firstName: 'Si',
    lastName: 'Nellies',
    email: 'snellies1d@go.com',
    favoriteAnimal: 'Monkey, rhesus',
  },
  {
    id: 51,
    firstName: 'Quillan',
    lastName: 'Tosh',
    email: 'qtosh1e@topsy.com',
    favoriteAnimal: 'Common nighthawk',
  },
  {
    id: 52,
    firstName: 'Griselda',
    lastName: 'Ackerley',
    email: 'gackerley1f@furl.net',
    favoriteAnimal: 'African wild dog',
  },
  {
    id: 53,
    firstName: 'Davie',
    lastName: 'Bredes',
    email: 'dbredes1g@opera.com',
    favoriteAnimal: 'Yellow-headed caracara',
  },
  {
    id: 54,
    firstName: 'Theodor',
    lastName: 'Broader',
    email: 'tbroader1h@mashable.com',
    favoriteAnimal: 'Lesser mouse lemur',
  },
  {
    id: 55,
    firstName: 'Johny',
    lastName: 'Camelli',
    email: 'jcamelli1i@people.com.cn',
    favoriteAnimal: 'Tern, white-winged black',
  },
  {
    id: 56,
    firstName: 'Corey',
    lastName: 'Anthona',
    email: 'canthona1j@shutterfly.com',
    favoriteAnimal: 'North American red fox',
  },
  {
    id: 57,
    firstName: 'Johnath',
    lastName: 'Hand',
    email: 'jhand1k@blog.com',
    favoriteAnimal: 'Moorhen, purple',
  },
  {
    id: 58,
    firstName: 'Clio',
    lastName: 'Dunderdale',
    email: 'cdunderdale1l@columbia.edu',
    favoriteAnimal: 'Buffalo, african',
  },
  {
    id: 59,
    firstName: 'Eloisa',
    lastName: 'Arnaud',
    email: 'earnaud1m@bbc.co.uk',
    favoriteAnimal: 'Blackbird, red-winged',
  },
  {
    id: 60,
    firstName: 'Nathalie',
    lastName: 'Matsell',
    email: 'nmatsell1n@miitbeian.gov.cn',
    favoriteAnimal: 'Sloth, pale-throated three-toed',
  },
  {
    id: 61,
    firstName: 'Quincy',
    lastName: 'Volker',
    email: 'qvolker1o@webmd.com',
    favoriteAnimal: 'Grenadier, purple',
  },
  {
    id: 62,
    firstName: 'Hercule',
    lastName: 'Aust',
    email: 'haust1p@chron.com',
    favoriteAnimal: 'Frilled dragon',
  },
  {
    id: 63,
    firstName: 'Anatollo',
    lastName: 'Gergler',
    email: 'agergler1q@utexas.edu',
    favoriteAnimal: 'Bulbul, african red-eyed',
  },
  {
    id: 64,
    firstName: 'Gorden',
    lastName: 'Harrisson',
    email: 'gharrisson1r@ow.ly',
    favoriteAnimal: 'Tenrec, tailless',
  },
  {
    id: 65,
    firstName: 'Antonia',
    lastName: 'Lotterington',
    email: 'alotterington1s@nature.com',
    favoriteAnimal: 'American marten',
  },
  {
    id: 66,
    firstName: 'Jenine',
    lastName: 'Odby',
    email: 'jodby1t@delicious.com',
    favoriteAnimal: 'Grouse, greater sage',
  },
  {
    id: 67,
    firstName: 'Morly',
    lastName: 'Liley',
    email: 'mliley1u@artisteer.com',
    favoriteAnimal: 'Starfish, crown of thorns',
  },
  {
    id: 68,
    firstName: 'Myca',
    lastName: 'Stuckey',
    email: 'mstuckey1v@issuu.com',
    favoriteAnimal: "Squirrel, smith's bush",
  },
  {
    id: 69,
    firstName: 'Cacilie',
    lastName: 'Tomala',
    email: 'ctomala1w@blogtalkradio.com',
    favoriteAnimal: 'Hudsonian godwit',
  },
  {
    id: 70,
    firstName: 'Ethelbert',
    lastName: 'Rodrigues',
    email: 'erodrigues1x@alexa.com',
    favoriteAnimal: 'Wildebeest, blue',
  },
  {
    id: 71,
    firstName: 'Edyth',
    lastName: 'De Cristoforo',
    email: 'edecristoforo1y@sbwire.com',
    favoriteAnimal: 'Harbor seal',
  },
  {
    id: 72,
    firstName: 'Benny',
    lastName: 'Eddie',
    email: 'beddie1z@ustream.tv',
    favoriteAnimal: 'Dolphin, bottle-nose',
  },
  {
    id: 73,
    firstName: 'Virgina',
    lastName: 'Gellan',
    email: 'vgellan20@theguardian.com',
    favoriteAnimal: 'Eagle owl (unidentified)',
  },
  {
    id: 74,
    firstName: 'Lance',
    lastName: 'Kapelhoff',
    email: 'lkapelhoff21@skype.com',
    favoriteAnimal: 'Goldeneye, common',
  },
  {
    id: 75,
    firstName: 'Rorke',
    lastName: 'Jozsika',
    email: 'rjozsika22@multiply.com',
    favoriteAnimal: 'Little grebe',
  },
  {
    id: 76,
    firstName: 'Henri',
    lastName: 'Frentz',
    email: 'hfrentz23@npr.org',
    favoriteAnimal: 'Dragon, komodo',
  },
  {
    id: 77,
    firstName: 'Bay',
    lastName: 'Worton',
    email: 'bworton24@1und1.de',
    favoriteAnimal: 'Tayra',
  },
  {
    id: 78,
    firstName: 'Jackie',
    lastName: 'Buckoke',
    email: 'jbuckoke25@paypal.com',
    favoriteAnimal: 'Shrike, crimson-breasted',
  },
  {
    id: 79,
    firstName: 'Gizela',
    lastName: 'Rawle',
    email: 'grawle26@boston.com',
    favoriteAnimal: 'Southern tamandua',
  },
  {
    id: 80,
    firstName: 'Winny',
    lastName: 'Lymer',
    email: 'wlymer27@wiley.com',
    favoriteAnimal: 'Brown hyena',
  },
  {
    id: 81,
    firstName: 'Philly',
    lastName: 'North',
    email: 'pnorth28@samsung.com',
    favoriteAnimal: 'Phalarope, northern',
  },
  {
    id: 82,
    firstName: 'Joanne',
    lastName: 'Blunsom',
    email: 'jblunsom29@vimeo.com',
    favoriteAnimal: 'Eagle, bateleur',
  },
  {
    id: 83,
    firstName: 'Lolita',
    lastName: 'Petracchi',
    email: 'lpetracchi2a@hostgator.com',
    favoriteAnimal: 'Capybara',
  },
  {
    id: 84,
    firstName: 'Cody',
    lastName: 'Gatland',
    email: 'cgatland2b@cnn.com',
    favoriteAnimal: 'Lizard, mexican beaded',
  },
  {
    id: 85,
    firstName: 'Evelin',
    lastName: 'Murfett',
    email: 'emurfett2c@elpais.com',
    favoriteAnimal: 'Tarantula, salmon pink bird eater',
  },
  {
    id: 86,
    firstName: 'Conrado',
    lastName: 'Dow',
    email: 'cdow2d@spiegel.de',
    favoriteAnimal: 'Long-tailed skua',
  },
  {
    id: 87,
    firstName: 'Jacky',
    lastName: 'McTeggart',
    email: 'jmcteggart2e@un.org',
    favoriteAnimal: 'Paddy heron (unidentified)',
  },
  {
    id: 88,
    firstName: 'Magdalena',
    lastName: 'Riddle',
    email: 'mriddle2f@hao123.com',
    favoriteAnimal: 'Jackal, indian',
  },
  {
    id: 89,
    firstName: 'Steffane',
    lastName: 'Marmion',
    email: 'smarmion2g@fema.gov',
    favoriteAnimal: 'Heron, gray',
  },
  {
    id: 90,
    firstName: 'Timothee',
    lastName: 'Fenning',
    email: 'tfenning2h@bbb.org',
    favoriteAnimal: 'African bush squirrel',
  },
  {
    id: 91,
    firstName: 'Gilli',
    lastName: 'Locker',
    email: 'glocker2i@abc.net.au',
    favoriteAnimal: 'White spoonbill',
  },
  {
    id: 92,
    firstName: 'Alan',
    lastName: 'Simyson',
    email: 'asimyson2j@google.nl',
    favoriteAnimal: 'Goose, cape barren',
  },
  {
    id: 93,
    firstName: 'Sharla',
    lastName: 'Ughini',
    email: 'sughini2k@csmonitor.com',
    favoriteAnimal: 'Eastern box turtle',
  },
  {
    id: 94,
    firstName: 'Hunter',
    lastName: 'Gwyther',
    email: 'hgwyther2l@over-blog.com',
    favoriteAnimal: 'Raccoon, common',
  },
  {
    id: 95,
    firstName: 'Almeta',
    lastName: 'Seel',
    email: 'aseel2m@cnn.com',
    favoriteAnimal: 'Capuchin, white-fronted',
  },
  {
    id: 96,
    firstName: 'Fidela',
    lastName: 'Goodwell',
    email: 'fgoodwell2n@opera.com',
    favoriteAnimal: 'Boa, malagasy ground',
  },
  {
    id: 97,
    firstName: 'Ellery',
    lastName: 'Christol',
    email: 'echristol2o@usa.gov',
    favoriteAnimal: 'Buffalo, asian water',
  },
  {
    id: 98,
    firstName: 'Hanan',
    lastName: 'Print',
    email: 'hprint2p@cnet.com',
    favoriteAnimal: 'Gull, dusky',
  },
  {
    id: 99,
    firstName: 'Allyce',
    lastName: 'Carles',
    email: 'acarles2q@shinystat.com',
    favoriteAnimal: 'Rabbit, eastern cottontail',
  },
  {
    id: 100,
    firstName: 'Omero',
    lastName: 'Frisby',
    email: 'ofrisby2r@answers.com',
    favoriteAnimal: 'Yellow-bellied marmot',
  },
]
